AzureWorkshop.Web/Models/Shared/ErrorViewModel.cs
namespace AzureWorkshop.Web.Models.Shared
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AzureWorkshop.Web/Models/Storage/CreateContainerViewModel.cs
namespace AzureWorkshop.Web.Models.Storage
{
    public class CreateContainerViewModel
    {
        public string ContainerName { get; set; } = string.Empty;
    }
}

AzureWorkshop.Web/Models/Storage/StorageViewModel.cs
using Azure.Storage.Blobs.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AzureWorkshop.Web.Models.Storage
{
    public class StorageViewModel
    {
        public string SelectedContainer { get; set; } = string.Empty;

        public List<SelectListItem>? Containers { get; set; }

        public List<BlobItem>? BlobItems { set; get; }
    }
}

AzureWorkshop.Web/Controllers/HomeController.cs
using AzureWorkshop.Web.Models.Shared;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AzureWorkshop.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AzureWorkshop.Web/Controllers/StorageController.cs
using AzureWorkshop.Web.Models.Storage;
using AzureWorkshop.Web.Services.Storage;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AzureWorkshop.Web.Controllers
{
    public class StorageController : Controller
    {
        private readonly IContainerService _containerService;

        public StorageController(IContainerService containerService)
        {
            _containerService = containerService;
        }

        [HttpGet]
        public IActionResult Index(string? container = "")
        {
            var model = new StorageViewModel();
            model.SelectedContainer = container;

            model.Containers =
            [
                new SelectListItem() { Text = "Select a Container...", Value = "" },
                .. _containerService.GetContainers().Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Name,
                    Selected = x.Name == container
                })
            ];

            if (!string.IsNullOrEmpty(container))
            {
                model.BlobItems = _containerService.GetContainerContents(container);
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult CreateContainer()
        {
            var model = new CreateContainerViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult CreateContainer(CreateContainerViewModel model)
        {
            if (ModelState.IsValid)
            {
                _containerService.CreateContainer(model.ContainerName);
                return RedirectToAction("Index", new { container = model.ContainerName});
            }

            return View();
        }

        [HttpPost]
        public IActionResult Upload(string containerName, IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                return BadRequest("No file uploaded.");
            }

            _containerService.UploadFile(containerName, file);
            return RedirectToAction("Index", new { container = containerName });
        }
    }
}

AzureWorkshop.Web/Views/Home/Index.cshtml
    @{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This little web app was created to showcase interactions with various Azure Services.</p>
</div>

AzureWorkshop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Azure Workshop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AzureWorkshop.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Azure Workshop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Storage" asp-action="Index">Blob Storage</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Azure Workshop
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AzureWorkshop.Web/Views/Storage/CreateContainer.cshtml
@model AzureWorkshop.Web.Models.Storage.CreateContainerViewModel

<form asp-action="CreateContainer" method="post">
    <div class="row">
        <div class="col-6 offset-6">
            <div class="input-group mb-3">
                <input asp-for="ContainerName" class="form-control" />
                <button class="btn btn-primary" type="submit">Create Container</button>
            </div>
        </div>
    </div>
</form>
<div class="alert alert-primary" role="alert">
    <p>Container name can only contain lower case letters and numbers. No spaces, hyphens, etc.</p>
</div>

AzureWorkshop.Web/Views/Storage/Index.cshtml
@model AzureWorkshop.Web.Models.Storage.StorageViewModel

<div class="row">
    <div class="col-4">
        <a class="btn btn-primary" asp-action="CreateContainer">Create Container</a>
    </div>
    <div class="col-4 offset-4">
        <div class="input-group mb-3">
            @Html.DropDownListFor(m => m.SelectedContainer, Model.Containers, new { @class = "form-select" })
            <button class="btn btn-outline-secondary" type="button" onclick="viewContainerContents_OnClick()">View Contents</button>
            <input type="hidden" id="containerBaseUrl" value="@Url.Action("Index", "Storage")" />
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        @if (Model.BlobItems != null && Model.BlobItems.Any())
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Access Tier</th>
                        <th>Last Modified</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.BlobItems)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.Properties.AccessTier</td>
                            <td>@item.Properties.LastModified</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div class="alert alert-secondary" role="alert">
                @if (string.IsNullOrEmpty(Model.SelectedContainer))
                {
                    <span>Select a container to view its contents.</span>
                }
                else
                {
                    <span>No items found in the container.</span>
                }
            </div>
        }

        @if (!string.IsNullOrEmpty(Model.SelectedContainer))
        {
            <form asp-action="Upload" method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="mt-3 col-6 offset-6">
                        <div class="input-group">
                            <input class="form-control" type="file" id="file" name="file">
                            <button class="btn btn-primary" type="submit">Upload</button>
                            <input type="hidden" name="containerName" value="@Model.SelectedContainer" />
                        </div>
                    </div>
                </div>
            </form>
        }
    </div>
</div>